@startuml

Title "Sentry Initialization"

actor User

box "Sentry" 
participant NetworkWorker 
participant MessageDistributor
participant SentinelWorker
participant DeviceIsx3
participant DeviceOb1
end box

autonumber 

User -> NetworkWorker : InitDeviceMessage
activate NetworkWorker
NetworkWorker -> MessageDistributor : InitDeviceMessage
deactivate NetworkWorker
activate MessageDistributor
MessageDistributor -> SentinelWorker : InitDeviceMessage
deactivate MessageDistributor
activate SentinelWorker
SentinelWorker -> MessageDistributor : DeviceIsx3InitMessage
activate MessageDistributor
SentinelWorker -> MessageDistributor : DeviceOb1InitMessage
MessageDistributor -> DeviceIsx3 : DeviceIsx3InitMessage
activate DeviceIsx3
MessageDistributor -> DeviceOb1 : DeviceOb1InitMessage
deactivate MessageDistributor
activate DeviceOb1
SentinelWorker -> DeviceIsx3 : GetState
activate DeviceIsx3
activate DeviceOb1
DeviceIsx3 --> SentinelWorker : Still Initializing
deactivate DeviceIsx3
SentinelWorker -> DeviceOb1 : GetState
DeviceOb1 --> SentinelWorker : Still Initializing 
deactivate DeviceOb1
deactivate DeviceOb1
deactivate DeviceIsx3

SentinelWorker -> DeviceIsx3 : GetState
activate DeviceIsx3
SentinelWorker -> DeviceOb1 : GetState
activate DeviceOb1
DeviceIsx3 --> SentinelWorker : Is initialized
deactivate DeviceIsx3
DeviceOb1 --> SentinelWorker : Is initialized 
deactivate DeviceOb1





deactivate SentinelWorker

@enduml