#ifndef READ_DEVICE_MESSAGE_HPP
#define READ_DEVICE_MESSAGE_HPP

// Project includes
#include <device_message.hpp>
#include <read_payload.hpp>
#include <write_device_message.hpp>

using namespace Devices;

namespace Messages {

/**
 * @brief Identifies the reason of the read message.
 */
enum ReadDeviceTopic {
  /// Invalid topic
  READ_TOPIC_INVALID,

  /// The message contains the status of the device.
  READ_TOPIC_DEVICE_STATUS,

  /// Message contains device image of an Elveflow OB1 device.
  READ_TOPIC_OB1_DEVICE_IMAGE
};

/**
 * A message that has been generated by a device in response to a
 * DeviceWriteMessage.
 */
class ReadDeviceMessage : public DeviceMessage {
public:
  /**
   * @brief Constructs the read device message with the given topic and
   * payload.
   * @param topic The topic of the message.
   * @param readPayload The payload of the message.
   */
  ReadDeviceMessage(ReadDeviceTopic topic, ReadPayload *readPayload);

  /**
   * @brief Serializes the message into a human-readable string.
   * @return The string representation of the message.
   */
  virtual string serialize() override;

  /**
   * @brief Return the payload of the message.
   * @return The payload, held by this message.
   */
  shared_ptr<ReadPayload> getReadPaylod();

private:
  /// Reference to the messsage this message is the response to.
  shared_ptr<WriteDeviceMessage> originalMessage;

  /// Reference to the payload.
  shared_ptr<ReadPayload> readPayload;

  /// The topic of the message.
  ReadDeviceTopic topic;
};
} // namespace Messages

#endif